import sys
import time
from pathlib import Path

import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.service import SmartLLMCacheService


st.set_page_config(
    page_title="SmartLLM Cache",
    page_icon="⚡",
    layout="centered",
)

st.title("⚡ SmartLLM Cache")
st.caption("Cache-first LLM routing: exact match → LLM fallback")

if "service" not in st.session_state:
    st.session_state.service = SmartLLMCacheService()

if "total_queries" not in st.session_state:
    st.session_state.total_queries = 0

if "cache_hits" not in st.session_state:
    st.session_state.cache_hits = 0

if "tokens_saved" not in st.session_state:
    st.session_state.tokens_saved = 0

top_left, top_right = st.columns([4, 1])

with top_right:
    if st.button("Reset demo"):
        st.session_state.service = SmartLLMCacheService()
        st.session_state.total_queries = 0
        st.session_state.cache_hits = 0
        st.session_state.tokens_saved = 0
        st.rerun()

query = st.text_input(
    "Ask a question",
    placeholder="Example: What is Python?",
)

if st.button("Ask", type="primary") and query.strip():
    start_time = time.perf_counter()

    with st.spinner("Checking cache and generating when needed..."):
        result = st.session_state.service.ask(query)

    latency_ms = (time.perf_counter() - start_time) * 1000
    st.session_state.total_queries += 1

    if result["source"] == "exact_cache":
        st.session_state.cache_hits += 1
        st.session_state.tokens_saved += result["tokens_saved"]

        st.success(
            f"Exact cache hit — LLM generation skipped. "
            f"Saved {result['tokens_saved']} tokens."
        )
    else:
        st.warning(
            "Cache miss — response was generated by the LLM fallback "
            "and saved for the next identical request."
        )

    st.subheader("Response")
    st.write(result["response"])

    st.subheader("Request details")
    metric_1, metric_2, metric_3 = st.columns(3)
    metric_1.metric("Response source", result["source"])
    metric_2.metric("Latency", f"{latency_ms:.1f} ms")
    metric_3.metric("Tokens saved", result["tokens_saved"])

st.divider()
st.subheader("Session metrics")

total_queries = st.session_state.total_queries
cache_hits = st.session_state.cache_hits
hit_rate = (cache_hits / total_queries * 100) if total_queries else 0

metric_1, metric_2, metric_3, metric_4 = st.columns(4)
metric_1.metric("Total queries", total_queries)
metric_2.metric("Exact cache hits", cache_hits)
metric_3.metric("Cache hit rate", f"{hit_rate:.1f}%")
metric_4.metric("Total tokens saved", st.session_state.tokens_saved)

st.caption("Tip: submit the same question twice to observe a cache hit.")