from time import sleep


class MockLLM:
    """Fake LLM used only to test cache behavior before real model integration."""

    def __init__(self, delay_seconds: float = 1.5) -> None:
        self.delay_seconds = delay_seconds

    def generate(self, query: str) -> tuple[str, int]:
        sleep(self.delay_seconds)

        response = (
            f"Generated answer for: {query}\n\n"
            "This answer was generated by the LLM fallback and saved in the cache."
        )
        tokens_generated = len(response.split())

        return response, tokens_generated 
